volumes:
  pihole-data: {}

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      TZ: 'Asia/Shanghai'
      WEBPASSWORD: ''
      DNS1: 223.5.5.5               # AliDNS
      DNS2: 119.29.29.29            # Tencent DNS
      DNSSEC: "false"               # Disable DNSSEC for better compatibility
      REV_SERVER: "true"            # Enable conditional forwarding
      #PROXY_SERVER: 'host.docker.internal:500'  # For VPN proxy
      #DNS1: 127.0.0.1#5053  # Local DNS resolver
      #DNS2: 1.1.1.1
    volumes:
      - 'pihole-data:/etc/pihole/'
      - './dnsmasq.d/:/etc/dnsmasq.d/'
      - './custom.list:/etc/pihole/custom.list'  # Local DNS entries
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
      - "5335:5335/tcp"
    #dns:
    #  - 127.0.0.1
    #  - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities