services:
  minecraft-without-mods:
    image: itzg/minecraft-server
    ports:
      - 25566:25565
    environment:
      VERSION: "1.20.1"
      SERVER_NAME: "The Civil War"
      MOTD: "§cWelcome to The Hell without Mods"
      EULA: "TRUE"
      ICON: "/extras/ico.png"
      OVERRIDE_ICON: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      INIT_MEMORY: 3G
      MAX_MEMORY: 6G

      TYPE: "PAPER"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ONLINE_MODE: "FALSE"
      EXEC_DIRECTLY: "TRUE"
      FORCE_GAMEMODE: "TRUE"
      MODE: "CREATIVE"
      DIFFICULTY: "HARD"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"

      RCON_CMDS_STARTUP: |-
        /gamerule doFireTick false
        /gamerule keepInventory false
      RCON_CMDS_ON_CONNECT: |-
        /op @p

    tty: true
    stdin_open: true
    restart: on-failure:1
    volumes:
      - D:/containers/minecraft-mods/extras/ico.png:/extras/ico.png:ro
      - D:/containers/minecraft-mods/minecraft-data-without-mods:/data
    deploy:
      resources:
        limits:
          cpus: "2"