version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      VERSION: "1.20.1"
      SERVER_NAME: "The Civil War"
      MOTD: "§cBienvenidas perras a §r §nServer" # The message of the day, shown below each server entry in the client UI
      EULA: "true" # By default the value should always be TRUE
      INIT_MEMORY: 6G
      MAX_MEMORY: 12G

      # Indicates type of the server if every is commented, default is vanilla
      #TYPE: "PAPER" # faster vanilla
      #TYPE: "FABRIC" # faster mods but not good
      TYPE: "FORGE" # Better mods
      FORGE_VERSION: "47.3.22"
      REMOVE_OLD_MODS: "TRUE"

      # If is forge or fabric indicate which moods gonna use
      MODS: "/modpacks/1.20.1/louya/BiomesOPlenty-forge-1.20.1-19.0.0.94.jar,\
             /modpacks/1.20.1/louya/carryon-forge-1.20.1-2.1.2.7.jar,\
             /modpacks/1.20.1/louya/GlitchCore-forge-1.20.1-0.0.1.1.jar,\
             /modpacks/1.20.1/louya/immersive_weathering-1.20.1-2.0.3-forge.jar,\
             /modpacks/1.20.1/louya/moonlight-1.20-2.13.46-forge.jar,\
             /modpacks/1.20.1/louya/tectonic-forge-1.20.1-2.4.1.jar,\
             /modpacks/1.20.1/louya/TerraBlender-forge-1.20.1-3.0.1.7.jar,\
             /modpacks/1.20.1/louya/Terralith_1.20.x_v2.5.4.jar,\
             /modpacks/1.20.1/aur/basic/curios-forge-5.11.1+1.20.1.jar,\
             /modpacks/1.20.1/aur/basic/L_Enders_Cataclysm-2.32- 1.20.1.jar,\
             /modpacks/1.20.1/aur/basic/lionfishapi-2.4-Fix.jar"

      #MODPACK: "/modpacks/1.20.1/aur/Better-MC-FORGE-1.20.1-v36.zip,\
      #          /modpacks/1.20.1/aur/Integrated-MC-1.3.6.zip"

      # Settings option
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ONLINE_MODE: "FALSE" # server checks connecting players against Minecraft's account database
      EXEC_DIRECTLY: "TRUE" # If you would like to docker attach to the Minecraft server console with color and interactive capabilities, then add
      FORCE_GAMEMODE: "TRUE"
      MODE: "CREATIVE"
      DIFFICULTY: "HARD"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE" # Allows server to announce when a player gets an achievement.

    tty: true
    stdin_open: true
    restart: on-failure:1
    volumes:
      - ./minecraft-data:/data
      - ./mods:/modpacks
      #- ./minecraft-plugins:/plugins
    deploy:
      resources:
        limits:
          cpus: "10"

        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]


# Monitoring
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft
      DEBUG: "true"
    depends_on:
      - minecraft
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus_manifest/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"

volumes:
  data: {}
  prometheus-tsdb: {}
  grafana-lib: {}