services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      VERSION: "1.20.1"
      SERVER_NAME: "The Civil War"
      MOTD: "§cBienvenidas perras to The Hell<3" # The message of the day, shown below each server entry in the client UI
      EULA: "true" # By default the value should always be TRUE
      ICON: "/extras/ico.png"
      OVERRIDE_ICON: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      INIT_MEMORY: 12G
      MAX_MEMORY: 20G

      # Indicates type of the server if every is commented, default is vanilla
      TYPE: "FORGE"
      FORGE_VERSION: "47.3.22"
      GENERIC_PACK: "/modpacks/Minecraft-Legendary-Edition-1.20.1-2.3.zip"

      # Settings option
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ONLINE_MODE: "FALSE" # server checks connecting players against Minecraft's account database
      EXEC_DIRECTLY: "TRUE" # If you would like to docker attach to the Minecraft server console with color and interactive capabilities, then add
      ENABLE_ROLLING_LOGS: "FALSE" # Delete old logs
      FORCE_GAMEMODE: "TRUE"
      MODE: "CREATIVE"
      DIFFICULTY: "EASY"
      ALLOW_FLIGHT: "TRUE"
      ALLOW_NETHER: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"

      RCON_CMDS_STARTUP: |-
        /gamerule keepInventory false
      RCON_CMDS_ON_CONNECT: |-
        /tell @p Welcome to The Hell, @p! Preparate pa'morir! 🎉
      #RCON_CMDS_FIRST_CONNECT: |-
      #  /pregen stop
      #RCON_CMDS_LAST_DISCONNECT: |-
      #  /kill @e[type=minecraft:boat]
      #  /pregen start 200

    tty: true
    stdin_open: true
    restart: on-failure:3
    volumes:
      - D:/containers/minecraft-mods/extras/mods.txt:/extras/mods.txt:ro
      - D:/containers/minecraft-mods/extras/ico.png:/extras/ico.png:ro
      - D:/containers/minecraft-mods/minecraft-data:/data
      - D:/containers/minecraft-mods/modpacks:/modpacks:ro
      #- D:/containers/minecraft-mods/mods:/mods:ro
