version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    #network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      # - ./media:/media
      - C:\\Users\\aurcode\\Videos\\Movies:/media/Movies
      - C:\\Users\\aurcode\\Videos\\Series:/media/Series
      #- C:\\Users\\aurcode\\files\\books:/media/books/general-books
      #- C:\\Users\\aurcode\\Desktop\\others-books:/media/books/others-books
      #- C:\\Users\\aurcode\\Desktop\\class-books:/media/books/class-books
      #- C:\\Users\\aurcode\\Desktop\\classes:/media/books/classes
      #- ./media2:/media2:ro
    ports:
      - 9000:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: 'unless-stopped'
    #extra_hosts:
    #- "host.docker.internal:host-gateway"
