global:
  scrape_interval: 1m
scrape_configs:
  - job_name: "mc-monitor"
    scrape_interval: 15s
    static_configs:
      - targets: ["mc-monitor:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
